# Generated by Django 6.1.1 on 2026-09-16 16:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EmotionIngredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60, unique=True)),
                ('emoji', models.CharField(default='✨', max_length=10)),
                ('color_hex', models.CharField(default='#FFD93D', help_text='Display color for UI chips', max_length=7)),
                ('css_class', models.CharField(default='chip-joy', help_text='CSS class name for styling', max_length=40)),
                ('category', models.CharField(choices=[('POSITIVE', 'Positive Vibes'), ('NEUTRAL', 'Neutral / Mixed'), ('HEAVY', 'Heavy Feels')], default='POSITIVE', max_length=10)),
            ],
            options={
                'ordering': ['category', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Potion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Give your potion a creative name', max_length=150)),
                ('vibe_rating', models.PositiveSmallIntegerField(default=5, help_text='Overall vibe from 1 (rough day) to 10 (absolutely magical)')),
                ('reflection', models.TextField(blank=True, help_text='Write about why you feel this way, what happened, or what you need')),
                ('is_favorite', models.BooleanField(default=False, help_text='Bookmark this as a favorite brew')),
                ('brewed_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('brewer', models.ForeignKey(help_text='The alchemist who brewed this potion', on_delete=django.db.models.deletion.CASCADE, related_name='potions', to=settings.AUTH_USER_MODEL)),
                ('ingredients', models.ManyToManyField(help_text='Select the emotions that went into this brew', related_name='used_in_potions', to='potions.emotioningredient')),
            ],
            options={
                'ordering': ['-brewed_at'],
            },
        ),
    ]
